### ISSUE TITLE
Simple Wallet Getting Error /json_rpc, wrong response code: 404

### ISSUE THREAD

**Issue by bangdrie** [chinet-project/chinet-core#1]
hii am getting this issue while run simple wallet

![image](https://user-images.githubusercontent.com/107682068/219850783-24e8c566-6510-415e-943c-e74642648a8f.png)

how to fix this issue ? thanks before

**Comment by chinet-developers** [comment]
No connection to daemon.
Run chinetd

**Comment by rikivinin** [comment]
hello, tell me, what is the problem? I can't configure stacking.stratum is working! 

.  here's the mistake.    2023-Mar-17 11:18:54.634087 Chinet wallet v1.5.1.143[]
2023-Mar-17 11:18:54.651088 Starting wallet RPC server...
2023-Mar-17 11:18:59.880387 Loading wallet...
2023-Mar-17 11:18:59.882387 [ERROR] Location: 
[tools::wallet2::load] @ C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662 Message:
e || !exists. THROW EXCEPTION: error::file_not_found
2023-Mar-17 11:18:59.911389 C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:18:59.913389 [ERROR] Location: 
[wmain] @ C:\Chinet-v1.0.8\chinet-core\src\simplewallet\simplewallet.cpp:2139 Message:
Wallet initialize failed: C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:20:09.167350 Chinet wallet v1.5.1.143[]
2023-Mar-17 11:20:09.169350 Starting wallet RPC server...
2023-Mar-17 11:20:22.361105 Loading wallet...
2023-Mar-17 11:20:22.362105 [ERROR] Location: 
[tools::wallet2::load] @ C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662 Message:
e || !exists. THROW EXCEPTION: error::file_not_found
2023-Mar-17 11:20:22.363105 C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:20:22.363105 [ERROR] Location: 
[wmain] @ C:\Chinet-v1.0.8\chinet-core\src\simplewallet\simplewallet.cpp:2139 Message:
Wallet initialize failed: C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:23:24.973550 Chinet wallet v1.5.1.143[]
2023-Mar-17 11:23:24.975550 Starting wallet RPC server...
2023-Mar-17 11:23:42.837571 Loading wallet...
2023-Mar-17 11:23:42.838571 [ERROR] Location: 
[tools::wallet2::load] @ C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662 Message:
e || !exists. THROW EXCEPTION: error::file_not_found
2023-Mar-17 11:23:42.839571 C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:23:42.840572 [ERROR] Location: 
[wmain] @ C:\Chinet-v1.0.8\chinet-core\src\simplewallet\simplewallet.cpp:2139 Message:
Wallet initialize failed: C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
