### ISSUE TITLE
steyk help

### ISSUE THREAD

**Issue by rikivinin** [chinet-project/chinet-core#3]
hello, tell me, what is the problem? I can't configure stacking.stratum is working! 

.  here's the mistake.    2023-Mar-17 11:18:54.634087 Chinet wallet v1.5.1.143[]
2023-Mar-17 11:18:54.651088 Starting wallet RPC server...
2023-Mar-17 11:18:59.880387 Loading wallet...
2023-Mar-17 11:18:59.882387 [ERROR] Location: 
[tools::wallet2::load] @ C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662 Message:
e || !exists. THROW EXCEPTION: error::file_not_found
2023-Mar-17 11:18:59.911389 C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:18:59.913389 [ERROR] Location: 
[wmain] @ C:\Chinet-v1.0.8\chinet-core\src\simplewallet\simplewallet.cpp:2139 Message:
Wallet initialize failed: C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:20:09.167350 Chinet wallet v1.5.1.143[]
2023-Mar-17 11:20:09.169350 Starting wallet RPC server...
2023-Mar-17 11:20:22.361105 Loading wallet...
2023-Mar-17 11:20:22.362105 [ERROR] Location: 
[tools::wallet2::load] @ C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662 Message:
e || !exists. THROW EXCEPTION: error::file_not_found
2023-Mar-17 11:20:22.363105 C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:20:22.363105 [ERROR] Location: 
[wmain] @ C:\Chinet-v1.0.8\chinet-core\src\simplewallet\simplewallet.cpp:2139 Message:
Wallet initialize failed: C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:23:24.973550 Chinet wallet v1.5.1.143[]
2023-Mar-17 11:23:24.975550 Starting wallet RPC server...
2023-Mar-17 11:23:42.837571 Loading wallet...
2023-Mar-17 11:23:42.838571 [ERROR] Location: 
[tools::wallet2::load] @ C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662 Message:
e || !exists. THROW EXCEPTION: error::file_not_found
2023-Mar-17 11:23:42.839571 C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"
2023-Mar-17 11:23:42.840572 [ERROR] Location: 
[wmain] @ C:\Chinet-v1.0.8\chinet-core\src\simplewallet\simplewallet.cpp:2139 Message:
Wallet initialize failed: C:\Chinet-v1.0.8\chinet-core\src\wallet\wallet2.cpp:2662:struct tools::error::file_error_base<1>: file not found "C:\Program"

**Comment by chinet-developers** [comment]
The path to the wallet file is incorrect

**Comment by rikivinin** [comment]
can you fix it? here is my bat file        simplewallet.exe 
![Безымянный](https://user-images.githubusercontent.com/128193413/226135640-d42966d6-4207-4a30-97ec-ae2d7822607b.jpg)
--wallet-file C:\Program Files\CHN\chinet-v1.5.1-gui-windows\coshelfail --do-pos-mining --pos-mining-reward-address ch1wHCkswMEUUg7yh6g7Z6Yt3nDUnWzsiAGj1GFtk3imBPHGL9zDpARUhhi9Z5fdFJ5fcjiuUFYZe2ST2Jwwspcv3345fewR8 --daemon-port 11211 --rpc-bind-port=11200 --disable-tor-relay

**Comment by rikivinin** [comment]
thank you I figured out how to fix the problem
